"""Rebuild ``config/stations.yaml`` from the live CPCB / data.gov.in feed.

The feed carries the authoritative station name and coordinates, so this produces a
registry with ``coords_verified: true``. Site-type is inferred from name keywords and
should be spot-checked. Existing hand-set ``site_type`` values are preserved on match.

    python -m ingest.stations_build            # write config/stations.generated.yaml
    python -m ingest.stations_build --promote  # also overwrite config/stations.yaml
"""

from __future__ import annotations

import argparse
import re

from config.settings import CONFIG_DIR, NCR_CITIES, SETTINGS, load_stations
from ingest.common import get_json, normalize_name
from ingest.cpcb import DATA_GOV_URL

_CITY_CODE = {
    "Delhi": "DEL",
    "Gurugram": "GGN",
    "Faridabad": "FBD",
    "Ghaziabad": "GZB",
    "Noida": "NOI",
    "Greater Noida": "GRN",
}

_SITE_TYPE_KEYWORDS: list[tuple[str, str]] = [
    (r"airport", "mixed"),
    (r"industr|udyog|okhla|bawana|mundka|narela|wazirpur|jahangirpuri|loni|new industrial", "industrial"),
    (r"anand vihar|ito|crri|mathura road|punjabi bagh|nehru nagar|dhyan chand|stadium|"
     r"mandir marg|sri aurobindo|sanjay nagar|vikas sadan", "traffic"),
    (r"dtu|iit|jnu|ignou|nsit|nsut|knowledge park|north campus|\bdu\b|aya nagar|"
     r"karni singh|teri gram|nise|pusa|lodhi|maidan garhi", "background"),
]


def _slug(name: str) -> str:
    s = normalize_name(name)
    s = s.split(" delhi")[0].split(" gurugram")[0].split(" faridabad")[0]
    s = s.split(" ghaziabad")[0].split(" noida")[0].split(" greater noida")[0]
    s = re.sub(r"\s+", "-", s.strip())
    return s or "site"


def _site_type(name: str, prior: dict[str, str]) -> str:
    key = normalize_name(name)
    if key in prior:
        return prior[key]
    low = key
    for pattern, label in _SITE_TYPE_KEYWORDS:
        if re.search(pattern, low):
            return label
    return "residential"


def build_yaml(limit: int = 8000) -> str:
    api_key = SETTINGS.data_gov_in_api_key
    if not api_key:
        raise SystemExit("DATA_GOV_IN_API_KEY required to rebuild the station registry")

    payload = get_json(
        DATA_GOV_URL, params={"api-key": api_key, "format": "json", "limit": limit}
    )
    records = payload.get("records", [])
    ncr_norms = {normalize_name(c) for c in NCR_CITIES}

    prior_site_type = {normalize_name(s.cpcb_name): s.site_type for s in load_stations()}
    prior_site_type.update({normalize_name(s.name): s.site_type for s in load_stations()})

    seen: dict[str, dict] = {}
    for rec in records:
        city = (rec.get("city") or "").strip()
        if normalize_name(city) not in ncr_norms:
            continue
        station = (rec.get("station") or "").strip()
        if not station or station in seen:
            continue
        try:
            lat = round(float(rec["latitude"]), 4)
            lon = round(float(rec["longitude"]), 4)
        except (TypeError, ValueError, KeyError):
            continue
        # display name = feed name minus the trailing ", City - AGENCY"
        disp = re.split(r",\s*[^,]*-\s*[A-Za-z]+\s*$", station)[0].strip() or station
        agency = station.rsplit("-", 1)[-1].strip() if "-" in station else "Unknown"
        code = _CITY_CODE.get(city, "NCR")
        seen[station] = {
            "id": f"{code}-{_slug(station)}",
            "name": disp,
            "city": city,
            "agency": agency,
            "lat": lat,
            "lon": lon,
            "site_type": _site_type(station, prior_site_type),
            "cpcb_name": station,
            "coords_verified": True,
        }

    rows = sorted(seen.values(), key=lambda r: (r["city"], r["name"]))
    # de-dupe ids (rare: same slug twice) by suffixing
    counts: dict[str, int] = {}
    for r in rows:
        counts[r["id"]] = counts.get(r["id"], 0) + 1
        if counts[r["id"]] > 1:
            r["id"] = f"{r['id']}-{counts[r['id']]}"

    lines = [
        "# Delhi NCR air-quality monitoring station registry.",
        "# GENERATED by `python -m ingest.stations_build` from the live data.gov.in CPCB feed.",
        "# Names + coordinates are authoritative (coords_verified: true). site_type is inferred.",
        "",
        "stations:",
    ]
    for r in rows:
        lines.append(
            f"  - {{id: {r['id']}, name: \"{r['name']}\", city: {r['city']}, "
            f"agency: {r['agency']}, lat: {r['lat']}, lon: {r['lon']}, "
            f"site_type: {r['site_type']}, coords_verified: true, "
            f"cpcb_name: \"{r['cpcb_name']}\"}}"
        )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(prog="ingest.stations_build", description=__doc__)
    ap.add_argument("--promote", action="store_true", help="overwrite config/stations.yaml")
    ap.add_argument("--limit", type=int, default=8000)
    args = ap.parse_args(argv)

    text = build_yaml(args.limit)
    gen = CONFIG_DIR / "stations.generated.yaml"
    gen.write_text(text, encoding="utf-8")
    n = text.count("\n  - {")
    print(f"wrote {gen} ({n} stations)")
    if args.promote:
        (CONFIG_DIR / "stations.yaml").write_text(text, encoding="utf-8")
        print(f"promoted -> {CONFIG_DIR / 'stations.yaml'}")


if __name__ == "__main__":
    main()
